### ISSUE TITLE
Troubles building YASR

### ISSUE THREAD

**Issue by l00mi** [Triply-Dev/YASGUI.YASR-deprecated#106]
Right now `npm run serve` fails with the error below, any hints?

node v8.1.2
npm 5.0.3

```
> yasgui-yasr@2.11.5 dev /Users/michael/Sandbox/YASGUI.YASR
> gulp serve

/Users/michael/Sandbox/YASGUI.YASR/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/Users/michael/Sandbox/YASGUI.YASR/node_modules/require-dir/index.js:97:37)
    at Object.<anonymous> (/Users/michael/Sandbox/YASGUI.YASR/gulpfile.js:1:85)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/Users/michael/Sandbox/YASGUI.YASR/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by LaurensRietveld** [comment]
I assume you mean `npm run dev`. Which npm version are you using. 5 by any chance?

**Comment by l00mi** [comment]
version are mentioned in top, and yes npm run dev !

**Comment by LaurensRietveld** [comment]
Ah, missed that one. This looks a lot like an npm5 issue I had yesterday with another project. Could you try removing the `package-lock.json` and running `npm install` again?

**Comment by l00mi** [comment]
`rm -r node_modules`, `rm package-lock.json` and npm install (libsass takes always lots of time, is it possible to get rid of this btw.? ) and then npm run dev ... same error unfortunately.

**Comment by LaurensRietveld** [comment]
Ah, I can now reproduce it after a switch to node v8. I'll take a look

**Comment by l00mi** [comment]
Thank you Laurens, that is great.

**Comment by LaurensRietveld** [comment]
This should be fixed now in yasr/yasqe/yasgui. could you try again?

**Comment by l00mi** [comment]
Perfect, able to serve and build smoothly now.
